### ISSUE TITLE
OSError: cannot identify image file

### ISSUE THREAD

**Issue by niddal-imam** [THUliumeng/end_to_end_sence_text_recognition#1]
After running end_to_end.py, I get this error message. Any suggestion
Use standard file APIs to check for files with this prefix.
Find 1 images
199 text boxes before nms
./test_img/img_demo.jpg : net 1258ms, restore 1ms, nms 2ms
[timing] 1.2700440883636475
loading pretrained model from /home/paperspace/Desktop/end_to_end_sence_text_recognition-master/crnn/crnn.pth
libpng warning: Image height is zero in IHDR
libpng error: Invalid IHDR data
Traceback (most recent call last):
  File "end_to_end.py", line 258, in <module>
    tf.app.run()
  File "/home/paperspace/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "end_to_end.py", line 240, in main
    image = Image.open(img_path).convert('L')
  File "/home/paperspace/.local/lib/python3.6/site-packages/PIL/Image.py", line 2687, in open
    % (filename if filename else fp))
OSError: cannot identify image file './output/word_area_img/word_area_img1.png'

**Comment by THUliumeng** [comment]
I guess this is the problem about file director.
